# Generated by Django 3.1 on 2020-08-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('overview', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=280)),
                ('path_img', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('text', models.CharField(max_length=280)),
                ('overview', models.CharField(max_length=64)),
                ('path_img', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
