# Generated by Django 3.0.8 on 2020-08-22 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('acces_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReducedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('shortened', models.CharField(max_length=32)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1_url.Token')),
            ],
        ),
    ]
