# Generated by Django 3.1 on 2020-09-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modifier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_uuid', models.UUIDField(editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=280)),
                ('refunded', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donations.coupon')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donations.playerdonation')),
            ],
        ),
        migrations.CreateModel(
            name='AccesCodeCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_code', models.CharField(max_length=32)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donations.coupon')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donations.playerdonation')),
            ],
        ),
    ]
