# Generated by Django 3.1 on 2020-09-06 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accescodecoupon',
            old_name='acces_code',
            new_name='access_code',
        ),
        migrations.AlterField(
            model_name='accescodecoupon',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.coupon'),
        ),
        migrations.AlterField(
            model_name='accescodecoupon',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.playerdonation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.playerdonation'),
        ),
    ]
